[flavor]
dark = "catppuccin-mocha"
light = "catppuccin-mocha"

[git]
modified = { fg = "#f9e2af" }
added = { fg = "#a6e3a1" }
untracked = { fg = "#94e2d5" }
ignored = { fg = "#6c7086" }
deleted = { fg = "#f38ba8" }
updated = { fg = "#fab387" }
clean = { fg = "#a6e3a1" }

modified_sign = "M"
added_sign = "A"
untracked_sign = "?"
ignored_sign = "I"
deleted_sign = "D"
updated_sign = "U"
clean_sign = ""
